// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JWTToken struct {
	_tab flatbuffers.Table
}

func GetRootAsJWTToken(buf []byte, offset flatbuffers.UOffsetT) *JWTToken {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JWTToken{}
	x.Init(buf, n+offset)
	return x
}

func FinishJWTTokenBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJWTToken(buf []byte, offset flatbuffers.UOffsetT) *JWTToken {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JWTToken{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJWTTokenBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JWTToken) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JWTToken) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JWTToken) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func JWTTokenStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func JWTTokenAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func JWTTokenEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
